name: サブモジュールからのイベント通知を受けて、サブモジュールを更新する

on:
  repository_dispatch:
    types: [submodule-updated]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .netrc for private submodule access
        run: | 
          echo -e "machine github.com\nlogin x-access-token\npassword ${{ secrets.SUBMODULE_PAT }}" > ~/.netrc
          
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_PAT }}

      - name: Update submodule to latest commit
        run: |
          git submodule update --remote src/content/posts
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add src/content/posts
            git commit -m "chore: サブモジュール更新"
            git push
          else
            echo "No submodule update needed."
          fi
